### ISSUE TITLE
IDEA 2021.2 Ultimate 好像使用不了这个插件

### ISSUE THREAD

**Issue by a-shy-coder** [yiyingcanfeng/maven-dependency-helper#6]
> 报错信息如下:
```markdown
com.intellij.diagnostic.PluginException: Cannot create class actions.MavenDependencyHelperAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Maven Dependency Helper, id=com.yiycf.plugins.mavenDependencyHelper, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\maven-dependency-helper-release.jar, version=2.1, package=null), packagePrefix=null, instanceId=82, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:870)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:887)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:180)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:512)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:501)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.addActionsFromActiveKeymap(IdeKeyEventDispatcher.java:840)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.updateCurrentContext(IdeKeyEventDispatcher.java:781)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:437)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:799)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalAccessException: no such constructor: actions.MavenDependencyHelperAction.<init>()void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: org/dom4j/DocumentException
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.dom4j.DocumentException PluginClassLoader(plugin=PluginDescriptor(name=Maven Dependency Helper, id=com.yiycf.plugins.mavenDependencyHelper, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\maven-dependency-helper-release.jar, version=2.1, package=null), packagePrefix=null, instanceId=82, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 28 more
```

**Comment by ycfeng** [comment]
是在插件市场里安装的吗？版本号是多少？

**Comment by a-shy-coder** [comment]
> 是在插件市场里安装的吗？版本号是多少？

对的, 在IDEA官网下载的, 然后本地安装的.
版本号是 2.1

**Comment by ycfeng** [comment]
2.3 版本已发布，可以再试试看  
[Releases v2.3](https://github.com/yiyingcanfeng/maven-dependency-helper/releases/tag/2.3)
